# Generated by Django 5.2.1 on 2025-05-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.professionalprofile'),
        ),
    ]
