# Generated by Django 5.2.1 on 2025-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('doctor', 'Doctor'), ('tutor', 'Tutor'), ('lawyer', 'Lawyer'), ('developer', 'Developer')], max_length=50)),
                ('bio', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
