# Generated by Django 5.2.1 on 2025-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
