# Generated by Django 5.2.1 on 2025-06-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_appointment_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='authentication.useraccount')),
            ],
        ),
    ]
