# Generated by Django 5.2.1 on 2025-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_freelanceravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceravailability',
            name='end_time',
            field=models.TimeField(default='9:0:0'),
            preserve_default=False,
        ),
    ]
