# Generated by Django 5.2.3 on 2025-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_freelanceravailability_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
